### ISSUE TITLE
Unfortunatly your banner photo is not visible in darkmode 

### ISSUE THREAD

**Issue by elenajp** [Cahllagerfeld/Cahllagerfeld#1]
<img width="1417" alt="Screenshot 2021-05-10 at 19 20 22" src="https://user-images.githubusercontent.com/53368353/117699337-02e27000-b1c5-11eb-9d2d-7778c26b4767.png">

I really love the banner photo of the trees. On Eddie's live stream it looked great with the white background but I went on your profile to follow you and realised that they don't fit with darkmode. Maybe they come in another colour? because it would great to keep them! 🌲🌲🌲🌲

**Comment by Cahllagerfeld** [comment]
Thx for reporting this issue! :D 

Exactly this came into my mind when eddie showed it :D

**Comment by Cahllagerfeld** [comment]
closed, moved from black to silver/grey

**Comment by elenajp** [comment]
No worries and have fun with your profile!
