### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [Cahllagerfeld/Cahllagerfeld#2]
Instead of Hello... Hola headline use the typing svg that I use in my profile: 
![screenshot](https://readme-typing-svg.herokuapp.com?size=50&center=true&vCenter=true&width=800&height=100&lines=Hello+World+%F0%9F%91%8B;Bonjour+tout+le+monde+%F0%9F%91%8B;Hallo+Welt%F0%9F%91%8B;Hello+World%F0%9F%91%8B)

**Comment by Cahllagerfeld** [comment]
Thx for raising! :D 
I normally dont like these typing animations 😅
But I kind of like it :D.
Give me some time until I decide 🤔

**Comment by ghost** [comment]
Ok @Cahllagerfeld I've already opened up a pr for that #3

**Comment by Cahllagerfeld** [comment]
closed, see #3
