### ISSUE TITLE
Join the Org

### ISSUE THREAD

**Issue by VasudevJaiswal** [Cahllagerfeld/Cahllagerfeld#7]
[Click Here](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)

**Comment by Cahllagerfeld** [comment]
I'm not interested sorry

**Comment by VasudevJaiswal** [comment]
Sorry For That
